### ISSUE TITLE
Update `KIWIX_READERS_SOURCES` with version 3.11.0 of kiwix android app.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [offspot/imager-service#425]
We have released the version [3.11.0](https://download.kiwix.org/release/kiwix-android/kiwix-3.11.0.apk) for the kiwix android, please update it in [KIWIX_READERS_SOURCES](https://github.com/offspot/imager-service/blob/096d19fc61d3461aefdcd79017e0b05a9ecf81c5/manager/manager/settings.py#L236C1-L236C22)

**Comment by kelson42** [comment]
@rgaudin I guess this should go aitomatically and immediatly a new kiwix release is done?!

**Comment by rgaudin** [comment]
> @rgaudin I guess this should go aitomatically and immediatly a new kiwix release is done?! Or maybe we should do something more sophisticated?

Only you can answer this question.
I am not involved in kiwix-android so my knowledge and trust is limited.
To me, it's an external software that I am bundling in cards that won't update.
Ideally, we'd want to test it and make sure it works are expected in this context before including it.
Since you are overseeing both project, we can assume this is your responsibility and skip this.

**Comment by kelson42** [comment]
@rgaudin To me all of this should stick to the web site

**Comment by rgaudin** [comment]
OK ; but website is updated manually…

**Comment by kelson42** [comment]
@rgaudin To me all of this should stick to the web site

No, website has permalinks (and if partly not, this is a bug)
